loot:
  base-minutes: 30
  reduce-minutes-per-zoeken-level: 2
  minimum-minutes: 5

wash:
  xp: 20
  cooldown-seconds: 60

walk:
  xp-per-block: 1
  quest-step-blocks: 100
  quest-xp: 25
  quest-cooldown-minutes: 30

feed:
  xp: 10
  base-cooldown-minutes: 10
  extra-minutes-per-eten-level: 1

drink:
  xp: 10
  base-cooldown-minutes: 10
  extra-minutes-per-water-level: 1

whistle:
  range-teleport: 5

follow:
  max-range: 40
  teleport-range: 15

hourly:
  cooldown-minutes: 60
  base-amount: 25
  command: "eco give %player% %amount%"

basket:
  itemsadder_id: "topia:dierenmand"

menu:
  itemsadder_id: "topia:dierenmand"

grinden:
  mining-speed-per-level: 0.005
  mining-speed-cap: 0.05

auraskills:
  trait-key: "mining_speed"

nametag:
  extra-y: 0.08

food-categories:
  katten:
    display-name: "Kattenvoer"
    itemsadder-id: "topia:kattenvoer"
    pet-types:
      - CAT

  honden:
    display-name: "Hondenvoer"
    itemsadder-id: "topia:hondenvoer"
    pet-types:
      - WOLF

  konijn:
    display-name: "Konijnenvoer"
    itemsadder-id: "topia:wortel"
    pet-types:
      - MYTHIC

