name: Pets
version: 1.0.0
main: org.Manonaise.pets.Pets
description: Pets plugin
api-version: "1.21"

dependencies:
  server:
    AuraSkills:
      load: BEFORE
      required: true
      join-classpath: true

    MythicMobs:
      load: BEFORE
      required: false
      join-classpath: true

    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  pet.command.give:
    default: op
  pet.command.remove:
    default: op
  pet.command.menu:
    default: false
  pet.command.menu.bypass:
    default: op
  pet.command.items.menu:
    default: true
  pet.command.whistle:
    default: true
  pet.command.givefood:
    default: op
